// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpeFCcUNVCYfC3ASlA_0VV0FvsQEVdMUE',
    appId: '1:633030793119:web:6b6b2a992af589fffa4faa',
    messagingSenderId: '633030793119',
    projectId: 'hellomate-8',
    authDomain: 'hellomate-8.firebaseapp.com',
    storageBucket: 'hellomate-8.firebasestorage.app',
    measurementId: 'G-ERER8BMMY6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpLF2bsdoOI17yRFDuUaRh62DQO4DkQNo',
    appId: '1:633030793119:android:79a4d4cb9a12d5d9fa4faa',
    messagingSenderId: '633030793119',
    projectId: 'hellomate-8',
    storageBucket: 'hellomate-8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9J4NjoQvOPFXOL-W09jshKfUxgT0JvS0',
    appId: '1:633030793119:ios:848faa14e78fb57dfa4faa',
    messagingSenderId: '633030793119',
    projectId: 'hellomate-8',
    storageBucket: 'hellomate-8.firebasestorage.app',
    iosBundleId: 'com.orchu.hellomate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9J4NjoQvOPFXOL-W09jshKfUxgT0JvS0',
    appId: '1:633030793119:ios:848faa14e78fb57dfa4faa',
    messagingSenderId: '633030793119',
    projectId: 'hellomate-8',
    storageBucket: 'hellomate-8.firebasestorage.app',
    iosBundleId: 'com.orchu.hellomate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCpeFCcUNVCYfC3ASlA_0VV0FvsQEVdMUE',
    appId: '1:633030793119:web:56655437bdec5fc0fa4faa',
    messagingSenderId: '633030793119',
    projectId: 'hellomate-8',
    authDomain: 'hellomate-8.firebaseapp.com',
    storageBucket: 'hellomate-8.firebasestorage.app',
    measurementId: 'G-M5HPV5JX58',
  );
}
